### ISSUE TITLE
Evoluir as Modelagens Complementares

### ISSUE THREAD

**Issue by guilacerda** [Desenho-1-2018-G-6/docs#30]
- [x] Identificar quais modelagens a mais se encaixam no nosso projeto.
- [x] Evoluir e/ou documentar tais modelagens

**Comment by affbedran** [comment]
Assim que o @guiaugusto fizer upload das paradas, podemos fechar essa issue.

**Comment by guiaugusto** [comment]
Fiz o upload das imagens e estou finalizando a documentação para inserir no repositório e na wiki.
